/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AltAccountRequest {
  'status' : AltLinkStatus,
  'requester' : User,
  'altAccount' : User,
  'createdAt' : Time,
}
export type AltLinkStatus = { 'revoked' : null } |
  { 'pending' : null } |
  { 'accepted' : null };
export interface ChatMessage {
  'id' : MessageId,
  'isDeleted' : boolean,
  'content' : string,
  'video' : [] | [ExternalBlob],
  'sender' : User,
  'timestamp' : Time,
  'image' : [] | [ExternalBlob],
  'roomId' : RoomId,
  'isPinned' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface IceCandidate { 'candidate' : string, 'sdpMLineIndex' : bigint }
export type MessageId = bigint;
export interface NewChatMessage {
  'content' : string,
  'video' : [] | [ExternalBlob],
  'image' : [] | [ExternalBlob],
  'roomId' : RoomId,
}
export interface Room {
  'id' : RoomId,
  'creator' : User,
  'name' : string,
  'createdAt' : Time,
}
export type RoomId = string;
export interface RoomMember { 'role' : RoomMemberRole, 'user' : User }
export type RoomMemberRole = { 'member' : null } |
  { 'admin' : null } |
  { 'moderator' : null } |
  { 'owner' : null };
export interface SavedServerLink {
  'code' : string,
  'savedAt' : Time,
  'serverId' : string,
}
export type SdpAnswer = string;
export type SdpOffer = string;
export interface Server {
  'id' : ServerId,
  'bio' : string,
  'owner' : User,
  'icon' : [] | [ExternalBlob],
  'name' : string,
  'createdAt' : Time,
  'banner' : [] | [ExternalBlob],
  'accentColor' : string,
}
export interface ServerAnnouncement {
  'id' : bigint,
  'isDeleted' : boolean,
  'content' : string,
  'video' : [] | [ExternalBlob],
  'author' : User,
  'timestamp' : Time,
  'image' : [] | [ExternalBlob],
  'isPinned' : boolean,
}
export type ServerId = string;
export type Time = bigint;
export type User = Principal;
export interface UserProfile {
  'bio' : string,
  'backgroundColor' : string,
  'avatarType' : string,
  'name' : string,
  'color' : string,
  'textOverlays' : string,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VoiceSessionState {
  'offer' : [] | [SdpOffer],
  'answer' : [] | [SdpAnswer],
  'iceCandidates' : Array<IceCandidate>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptAltAccount' : ActorMethod<[Principal], undefined>,
  'acceptFriendRequest' : ActorMethod<[User], undefined>,
  'addIceCandidate' : ActorMethod<[RoomId, IceCandidate], undefined>,
  'addUserToRoom' : ActorMethod<[RoomId, User], undefined>,
  'addUserToServer' : ActorMethod<[ServerId, User], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRoomMemberRole' : ActorMethod<
    [RoomId, User, RoomMemberRole],
    undefined
  >,
  'blockUser' : ActorMethod<[User], undefined>,
  'createRoom' : ActorMethod<[string], RoomId>,
  'createServer' : ActorMethod<
    [string],
    {
      'id' : ServerId,
      'bio' : string,
      'owner' : User,
      'icon' : [] | [ExternalBlob],
      'name' : string,
      'createdAt' : Time,
      'banner' : [] | [ExternalBlob],
      'accentColor' : string,
    }
  >,
  'deleteMessage' : ActorMethod<[RoomId, MessageId], undefined>,
  'deleteRoom' : ActorMethod<[RoomId], boolean>,
  'deleteServer' : ActorMethod<[ServerId], boolean>,
  'deleteServerAnnouncement' : ActorMethod<[ServerId, bigint], undefined>,
  'editMessage' : ActorMethod<[RoomId, MessageId, string], undefined>,
  'editServerAnnouncement' : ActorMethod<[ServerId, bigint, string], undefined>,
  'endVoiceSession' : ActorMethod<[RoomId], undefined>,
  'fetchMessages' : ActorMethod<
    [RoomId, MessageId, bigint],
    Array<ChatMessage>
  >,
  'generateServerInviteCode' : ActorMethod<[ServerId], string>,
  'getActiveMembers' : ActorMethod<[ServerId], Array<User>>,
  'getCallerFriends' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLinkedAltAccounts' : ActorMethod<[], Array<Principal>>,
  'getPendingAltRequests' : ActorMethod<
    [],
    {
      'incoming' : Array<AltAccountRequest>,
      'outgoing' : Array<AltAccountRequest>,
    }
  >,
  'getRoom' : ActorMethod<[RoomId], [] | [Room]>,
  'getRoomMembers' : ActorMethod<[RoomId], Array<RoomMember>>,
  'getRoomMembersWithPresence' : ActorMethod<[RoomId], Array<[User, boolean]>>,
  'getServerAccentColor' : ActorMethod<[ServerId], string>,
  'getServerAnnouncements' : ActorMethod<
    [ServerId, bigint, bigint],
    Array<ServerAnnouncement>
  >,
  'getServerBanner' : ActorMethod<[ServerId], [] | [ExternalBlob]>,
  'getServerBio' : ActorMethod<[ServerId], string>,
  'getServerIcon' : ActorMethod<[ServerId], [] | [ExternalBlob]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserServers' : ActorMethod<[User], Array<Server>>,
  'getVoiceSessionState' : ActorMethod<[RoomId], [] | [VoiceSessionState]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinServerWithInvite' : ActorMethod<[string], ServerId>,
  'kickRoomMember' : ActorMethod<[RoomId, User], undefined>,
  'linkAltAccount' : ActorMethod<[Principal], undefined>,
  'listRooms' : ActorMethod<[], Array<Room>>,
  'listSavedServerLinks' : ActorMethod<[], Array<SavedServerLink>>,
  'postMessage' : ActorMethod<[NewChatMessage], MessageId>,
  'postServerAnnouncement' : ActorMethod<
    [ServerId, string, [] | [ExternalBlob], [] | [ExternalBlob]],
    undefined
  >,
  'removeSavedServerLink' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveServerLink' : ActorMethod<[string, string], undefined>,
  'searchUsersByName' : ActorMethod<[string], Array<UserProfile>>,
  'sendFriendRequest' : ActorMethod<[User], undefined>,
  'sendSdpAnswer' : ActorMethod<[RoomId, SdpAnswer], undefined>,
  'sendSdpOffer' : ActorMethod<[RoomId, SdpOffer], undefined>,
  'setServerAccentColor' : ActorMethod<[ServerId, string], undefined>,
  'setServerBanner' : ActorMethod<[ServerId, [] | [ExternalBlob]], undefined>,
  'setServerBio' : ActorMethod<[ServerId, string], undefined>,
  'setServerIcon' : ActorMethod<[ServerId, [] | [ExternalBlob]], undefined>,
  'startVoiceSession' : ActorMethod<[RoomId], undefined>,
  'togglePin' : ActorMethod<[RoomId, MessageId, boolean], undefined>,
  'toggleServerPin' : ActorMethod<[ServerId, bigint, boolean], undefined>,
  'unblockUser' : ActorMethod<[User], undefined>,
  'unlinkAltAccount' : ActorMethod<[Principal], undefined>,
  'updatePresence' : ActorMethod<[boolean], undefined>,
  'updateRoomPresence' : ActorMethod<[RoomId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];