/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const User = IDL.Principal;
export const RoomId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MessageId = IDL.Nat;
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ChatMessage = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'sender' : User,
  'timestamp' : Time,
  'image' : IDL.Opt(ExternalBlob),
  'roomId' : RoomId,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'backgroundColor' : IDL.Text,
  'avatarType' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'textOverlays' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const Room = IDL.Record({
  'id' : RoomId,
  'creator' : User,
  'name' : IDL.Text,
  'createdAt' : Time,
});
export const NewChatMessage = IDL.Record({
  'content' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'roomId' : RoomId,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptFriendRequest' : IDL.Func([User], [], []),
  'addUserToRoom' : IDL.Func([RoomId, User], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([User], [], []),
  'createRoom' : IDL.Func([IDL.Text], [RoomId], []),
  'fetchMessages' : IDL.Func(
      [RoomId, MessageId, IDL.Nat],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getCallerFriends' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'postMessage' : IDL.Func([NewChatMessage], [MessageId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUsersByName' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'sendFriendRequest' : IDL.Func([User], [], []),
  'unblockUser' : IDL.Func([User], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const User = IDL.Principal;
  const RoomId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MessageId = IDL.Nat;
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ChatMessage = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'sender' : User,
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
    'roomId' : RoomId,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'backgroundColor' : IDL.Text,
    'avatarType' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'textOverlays' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const Room = IDL.Record({
    'id' : RoomId,
    'creator' : User,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  const NewChatMessage = IDL.Record({
    'content' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'roomId' : RoomId,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptFriendRequest' : IDL.Func([User], [], []),
    'addUserToRoom' : IDL.Func([RoomId, User], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([User], [], []),
    'createRoom' : IDL.Func([IDL.Text], [RoomId], []),
    'fetchMessages' : IDL.Func(
        [RoomId, MessageId, IDL.Nat],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getCallerFriends' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'postMessage' : IDL.Func([NewChatMessage], [MessageId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUsersByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'sendFriendRequest' : IDL.Func([User], [], []),
    'unblockUser' : IDL.Func([User], [], []),
  });
};

export const init = ({ IDL }) => { return []; };