/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const User = IDL.Principal;
export const RoomId = IDL.Text;
export const IceCandidate = IDL.Record({
  'candidate' : IDL.Text,
  'sdpMLineIndex' : IDL.Nat,
});
export const ServerId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RoomMemberRole = IDL.Variant({
  'member' : IDL.Null,
  'admin' : IDL.Null,
  'moderator' : IDL.Null,
  'owner' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const MessageId = IDL.Nat;
export const ChatMessage = IDL.Record({
  'id' : MessageId,
  'isDeleted' : IDL.Bool,
  'content' : IDL.Text,
  'video' : IDL.Opt(ExternalBlob),
  'sender' : User,
  'timestamp' : Time,
  'image' : IDL.Opt(ExternalBlob),
  'roomId' : RoomId,
  'isPinned' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'backgroundColor' : IDL.Text,
  'avatarType' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'textOverlays' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const AltLinkStatus = IDL.Variant({
  'revoked' : IDL.Null,
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
});
export const AltAccountRequest = IDL.Record({
  'status' : AltLinkStatus,
  'requester' : User,
  'altAccount' : User,
  'createdAt' : Time,
});
export const Room = IDL.Record({
  'id' : RoomId,
  'creator' : User,
  'name' : IDL.Text,
  'createdAt' : Time,
});
export const RoomMember = IDL.Record({
  'role' : RoomMemberRole,
  'user' : User,
});
export const ServerAnnouncement = IDL.Record({
  'id' : IDL.Nat,
  'isDeleted' : IDL.Bool,
  'content' : IDL.Text,
  'video' : IDL.Opt(ExternalBlob),
  'author' : User,
  'timestamp' : Time,
  'image' : IDL.Opt(ExternalBlob),
  'isPinned' : IDL.Bool,
});
export const Server = IDL.Record({
  'id' : ServerId,
  'bio' : IDL.Text,
  'owner' : User,
  'icon' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'createdAt' : Time,
  'banner' : IDL.Opt(ExternalBlob),
  'accentColor' : IDL.Text,
});
export const SdpOffer = IDL.Text;
export const SdpAnswer = IDL.Text;
export const VoiceSessionState = IDL.Record({
  'offer' : IDL.Opt(SdpOffer),
  'answer' : IDL.Opt(SdpAnswer),
  'iceCandidates' : IDL.Vec(IceCandidate),
});
export const SavedServerLink = IDL.Record({
  'code' : IDL.Text,
  'savedAt' : Time,
  'serverId' : IDL.Text,
});
export const NewChatMessage = IDL.Record({
  'content' : IDL.Text,
  'video' : IDL.Opt(ExternalBlob),
  'image' : IDL.Opt(ExternalBlob),
  'roomId' : RoomId,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptAltAccount' : IDL.Func([IDL.Principal], [], []),
  'acceptFriendRequest' : IDL.Func([User], [], []),
  'addIceCandidate' : IDL.Func([RoomId, IceCandidate], [], []),
  'addUserToRoom' : IDL.Func([RoomId, User], [], []),
  'addUserToServer' : IDL.Func([ServerId, User], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRoomMemberRole' : IDL.Func([RoomId, User, RoomMemberRole], [], []),
  'blockUser' : IDL.Func([User], [], []),
  'createRoom' : IDL.Func([IDL.Text], [RoomId], []),
  'createServer' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'id' : ServerId,
          'bio' : IDL.Text,
          'owner' : User,
          'icon' : IDL.Opt(ExternalBlob),
          'name' : IDL.Text,
          'createdAt' : Time,
          'banner' : IDL.Opt(ExternalBlob),
          'accentColor' : IDL.Text,
        }),
      ],
      [],
    ),
  'deleteMessage' : IDL.Func([RoomId, MessageId], [], []),
  'deleteRoom' : IDL.Func([RoomId], [IDL.Bool], []),
  'deleteServer' : IDL.Func([ServerId], [IDL.Bool], []),
  'deleteServerAnnouncement' : IDL.Func([ServerId, IDL.Nat], [], []),
  'editMessage' : IDL.Func([RoomId, MessageId, IDL.Text], [], []),
  'editServerAnnouncement' : IDL.Func([ServerId, IDL.Nat, IDL.Text], [], []),
  'endVoiceSession' : IDL.Func([RoomId], [], []),
  'fetchMessages' : IDL.Func(
      [RoomId, MessageId, IDL.Nat],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'generateServerInviteCode' : IDL.Func([ServerId], [IDL.Text], []),
  'getActiveMembers' : IDL.Func([ServerId], [IDL.Vec(User)], ['query']),
  'getCallerFriends' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLinkedAltAccounts' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getPendingAltRequests' : IDL.Func(
      [],
      [
        IDL.Record({
          'incoming' : IDL.Vec(AltAccountRequest),
          'outgoing' : IDL.Vec(AltAccountRequest),
        }),
      ],
      ['query'],
    ),
  'getRoom' : IDL.Func([RoomId], [IDL.Opt(Room)], ['query']),
  'getRoomMembers' : IDL.Func([RoomId], [IDL.Vec(RoomMember)], ['query']),
  'getRoomMembersWithPresence' : IDL.Func(
      [RoomId],
      [IDL.Vec(IDL.Tuple(User, IDL.Bool))],
      ['query'],
    ),
  'getServerAccentColor' : IDL.Func([ServerId], [IDL.Text], ['query']),
  'getServerAnnouncements' : IDL.Func(
      [ServerId, IDL.Nat, IDL.Nat],
      [IDL.Vec(ServerAnnouncement)],
      ['query'],
    ),
  'getServerBanner' : IDL.Func([ServerId], [IDL.Opt(ExternalBlob)], ['query']),
  'getServerBio' : IDL.Func([ServerId], [IDL.Text], ['query']),
  'getServerIcon' : IDL.Func([ServerId], [IDL.Opt(ExternalBlob)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserServers' : IDL.Func([User], [IDL.Vec(Server)], ['query']),
  'getVoiceSessionState' : IDL.Func(
      [RoomId],
      [IDL.Opt(VoiceSessionState)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinServerWithInvite' : IDL.Func([IDL.Text], [ServerId], []),
  'kickRoomMember' : IDL.Func([RoomId, User], [], []),
  'linkAltAccount' : IDL.Func([IDL.Principal], [], []),
  'listRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'listSavedServerLinks' : IDL.Func([], [IDL.Vec(SavedServerLink)], ['query']),
  'postMessage' : IDL.Func([NewChatMessage], [MessageId], []),
  'postServerAnnouncement' : IDL.Func(
      [ServerId, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'removeSavedServerLink' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveServerLink' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'searchUsersByName' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'sendFriendRequest' : IDL.Func([User], [], []),
  'sendSdpAnswer' : IDL.Func([RoomId, SdpAnswer], [], []),
  'sendSdpOffer' : IDL.Func([RoomId, SdpOffer], [], []),
  'setServerAccentColor' : IDL.Func([ServerId, IDL.Text], [], []),
  'setServerBanner' : IDL.Func([ServerId, IDL.Opt(ExternalBlob)], [], []),
  'setServerBio' : IDL.Func([ServerId, IDL.Text], [], []),
  'setServerIcon' : IDL.Func([ServerId, IDL.Opt(ExternalBlob)], [], []),
  'startVoiceSession' : IDL.Func([RoomId], [], []),
  'togglePin' : IDL.Func([RoomId, MessageId, IDL.Bool], [], []),
  'toggleServerPin' : IDL.Func([ServerId, IDL.Nat, IDL.Bool], [], []),
  'unblockUser' : IDL.Func([User], [], []),
  'unlinkAltAccount' : IDL.Func([IDL.Principal], [], []),
  'updatePresence' : IDL.Func([IDL.Bool], [], []),
  'updateRoomPresence' : IDL.Func([RoomId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const User = IDL.Principal;
  const RoomId = IDL.Text;
  const IceCandidate = IDL.Record({
    'candidate' : IDL.Text,
    'sdpMLineIndex' : IDL.Nat,
  });
  const ServerId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RoomMemberRole = IDL.Variant({
    'member' : IDL.Null,
    'admin' : IDL.Null,
    'moderator' : IDL.Null,
    'owner' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const MessageId = IDL.Nat;
  const ChatMessage = IDL.Record({
    'id' : MessageId,
    'isDeleted' : IDL.Bool,
    'content' : IDL.Text,
    'video' : IDL.Opt(ExternalBlob),
    'sender' : User,
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
    'roomId' : RoomId,
    'isPinned' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'backgroundColor' : IDL.Text,
    'avatarType' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'textOverlays' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const AltLinkStatus = IDL.Variant({
    'revoked' : IDL.Null,
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const AltAccountRequest = IDL.Record({
    'status' : AltLinkStatus,
    'requester' : User,
    'altAccount' : User,
    'createdAt' : Time,
  });
  const Room = IDL.Record({
    'id' : RoomId,
    'creator' : User,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  const RoomMember = IDL.Record({ 'role' : RoomMemberRole, 'user' : User });
  const ServerAnnouncement = IDL.Record({
    'id' : IDL.Nat,
    'isDeleted' : IDL.Bool,
    'content' : IDL.Text,
    'video' : IDL.Opt(ExternalBlob),
    'author' : User,
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
    'isPinned' : IDL.Bool,
  });
  const Server = IDL.Record({
    'id' : ServerId,
    'bio' : IDL.Text,
    'owner' : User,
    'icon' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'createdAt' : Time,
    'banner' : IDL.Opt(ExternalBlob),
    'accentColor' : IDL.Text,
  });
  const SdpOffer = IDL.Text;
  const SdpAnswer = IDL.Text;
  const VoiceSessionState = IDL.Record({
    'offer' : IDL.Opt(SdpOffer),
    'answer' : IDL.Opt(SdpAnswer),
    'iceCandidates' : IDL.Vec(IceCandidate),
  });
  const SavedServerLink = IDL.Record({
    'code' : IDL.Text,
    'savedAt' : Time,
    'serverId' : IDL.Text,
  });
  const NewChatMessage = IDL.Record({
    'content' : IDL.Text,
    'video' : IDL.Opt(ExternalBlob),
    'image' : IDL.Opt(ExternalBlob),
    'roomId' : RoomId,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptAltAccount' : IDL.Func([IDL.Principal], [], []),
    'acceptFriendRequest' : IDL.Func([User], [], []),
    'addIceCandidate' : IDL.Func([RoomId, IceCandidate], [], []),
    'addUserToRoom' : IDL.Func([RoomId, User], [], []),
    'addUserToServer' : IDL.Func([ServerId, User], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRoomMemberRole' : IDL.Func([RoomId, User, RoomMemberRole], [], []),
    'blockUser' : IDL.Func([User], [], []),
    'createRoom' : IDL.Func([IDL.Text], [RoomId], []),
    'createServer' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'id' : ServerId,
            'bio' : IDL.Text,
            'owner' : User,
            'icon' : IDL.Opt(ExternalBlob),
            'name' : IDL.Text,
            'createdAt' : Time,
            'banner' : IDL.Opt(ExternalBlob),
            'accentColor' : IDL.Text,
          }),
        ],
        [],
      ),
    'deleteMessage' : IDL.Func([RoomId, MessageId], [], []),
    'deleteRoom' : IDL.Func([RoomId], [IDL.Bool], []),
    'deleteServer' : IDL.Func([ServerId], [IDL.Bool], []),
    'deleteServerAnnouncement' : IDL.Func([ServerId, IDL.Nat], [], []),
    'editMessage' : IDL.Func([RoomId, MessageId, IDL.Text], [], []),
    'editServerAnnouncement' : IDL.Func([ServerId, IDL.Nat, IDL.Text], [], []),
    'endVoiceSession' : IDL.Func([RoomId], [], []),
    'fetchMessages' : IDL.Func(
        [RoomId, MessageId, IDL.Nat],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'generateServerInviteCode' : IDL.Func([ServerId], [IDL.Text], []),
    'getActiveMembers' : IDL.Func([ServerId], [IDL.Vec(User)], ['query']),
    'getCallerFriends' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLinkedAltAccounts' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getPendingAltRequests' : IDL.Func(
        [],
        [
          IDL.Record({
            'incoming' : IDL.Vec(AltAccountRequest),
            'outgoing' : IDL.Vec(AltAccountRequest),
          }),
        ],
        ['query'],
      ),
    'getRoom' : IDL.Func([RoomId], [IDL.Opt(Room)], ['query']),
    'getRoomMembers' : IDL.Func([RoomId], [IDL.Vec(RoomMember)], ['query']),
    'getRoomMembersWithPresence' : IDL.Func(
        [RoomId],
        [IDL.Vec(IDL.Tuple(User, IDL.Bool))],
        ['query'],
      ),
    'getServerAccentColor' : IDL.Func([ServerId], [IDL.Text], ['query']),
    'getServerAnnouncements' : IDL.Func(
        [ServerId, IDL.Nat, IDL.Nat],
        [IDL.Vec(ServerAnnouncement)],
        ['query'],
      ),
    'getServerBanner' : IDL.Func(
        [ServerId],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getServerBio' : IDL.Func([ServerId], [IDL.Text], ['query']),
    'getServerIcon' : IDL.Func([ServerId], [IDL.Opt(ExternalBlob)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserServers' : IDL.Func([User], [IDL.Vec(Server)], ['query']),
    'getVoiceSessionState' : IDL.Func(
        [RoomId],
        [IDL.Opt(VoiceSessionState)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinServerWithInvite' : IDL.Func([IDL.Text], [ServerId], []),
    'kickRoomMember' : IDL.Func([RoomId, User], [], []),
    'linkAltAccount' : IDL.Func([IDL.Principal], [], []),
    'listRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'listSavedServerLinks' : IDL.Func(
        [],
        [IDL.Vec(SavedServerLink)],
        ['query'],
      ),
    'postMessage' : IDL.Func([NewChatMessage], [MessageId], []),
    'postServerAnnouncement' : IDL.Func(
        [ServerId, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'removeSavedServerLink' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveServerLink' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'searchUsersByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'sendFriendRequest' : IDL.Func([User], [], []),
    'sendSdpAnswer' : IDL.Func([RoomId, SdpAnswer], [], []),
    'sendSdpOffer' : IDL.Func([RoomId, SdpOffer], [], []),
    'setServerAccentColor' : IDL.Func([ServerId, IDL.Text], [], []),
    'setServerBanner' : IDL.Func([ServerId, IDL.Opt(ExternalBlob)], [], []),
    'setServerBio' : IDL.Func([ServerId, IDL.Text], [], []),
    'setServerIcon' : IDL.Func([ServerId, IDL.Opt(ExternalBlob)], [], []),
    'startVoiceSession' : IDL.Func([RoomId], [], []),
    'togglePin' : IDL.Func([RoomId, MessageId, IDL.Bool], [], []),
    'toggleServerPin' : IDL.Func([ServerId, IDL.Nat, IDL.Bool], [], []),
    'unblockUser' : IDL.Func([User], [], []),
    'unlinkAltAccount' : IDL.Func([IDL.Principal], [], []),
    'updatePresence' : IDL.Func([IDL.Bool], [], []),
    'updateRoomPresence' : IDL.Func([RoomId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };