/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AltAccountRequest {
  'status' : AltLinkStatus,
  'requester' : User,
  'altAccount' : User,
  'createdAt' : Time,
}
export type AltLinkStatus = { 'revoked' : null } |
  { 'pending' : null } |
  { 'accepted' : null };
export interface ChatMessage {
  'id' : MessageId,
  'content' : string,
  'sender' : User,
  'timestamp' : Time,
  'image' : [] | [ExternalBlob],
  'roomId' : RoomId,
}
export type ExternalBlob = Uint8Array;
export interface IceCandidate { 'candidate' : string, 'sdpMLineIndex' : bigint }
export type MessageId = bigint;
export interface NewChatMessage {
  'content' : string,
  'image' : [] | [ExternalBlob],
  'roomId' : RoomId,
}
export interface Room {
  'id' : RoomId,
  'creator' : User,
  'name' : string,
  'createdAt' : Time,
}
export type RoomId = string;
export type SdpAnswer = string;
export type SdpOffer = string;
export interface Server {
  'id' : ServerId,
  'owner' : User,
  'name' : string,
  'createdAt' : Time,
}
export type ServerId = string;
export type Time = bigint;
export type User = Principal;
export interface UserProfile {
  'bio' : string,
  'backgroundColor' : string,
  'avatarType' : string,
  'name' : string,
  'color' : string,
  'textOverlays' : string,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VoiceSessionState {
  'offer' : [] | [SdpOffer],
  'answer' : [] | [SdpAnswer],
  'iceCandidates' : Array<IceCandidate>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptAltAccount' : ActorMethod<[Principal], undefined>,
  'acceptFriendRequest' : ActorMethod<[User], undefined>,
  'addIceCandidate' : ActorMethod<[RoomId, IceCandidate], undefined>,
  'addUserToRoom' : ActorMethod<[RoomId, User], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[User], undefined>,
  'createRoom' : ActorMethod<[string], RoomId>,
  'createServer' : ActorMethod<
    [string],
    { 'id' : ServerId, 'owner' : User, 'name' : string, 'createdAt' : Time }
  >,
  'endVoiceSession' : ActorMethod<[RoomId], undefined>,
  'fetchMessages' : ActorMethod<
    [RoomId, MessageId, bigint],
    Array<ChatMessage>
  >,
  'getCallerFriends' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLinkedAltAccounts' : ActorMethod<[], Array<Principal>>,
  'getPendingAltRequests' : ActorMethod<
    [],
    {
      'incoming' : Array<AltAccountRequest>,
      'outgoing' : Array<AltAccountRequest>,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserServers' : ActorMethod<[User], Array<Server>>,
  'getVoiceSessionState' : ActorMethod<[RoomId], [] | [VoiceSessionState]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkAltAccount' : ActorMethod<[Principal], undefined>,
  'listRooms' : ActorMethod<[], Array<Room>>,
  'postMessage' : ActorMethod<[NewChatMessage], MessageId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsersByName' : ActorMethod<[string], Array<UserProfile>>,
  'sendFriendRequest' : ActorMethod<[User], undefined>,
  'sendSdpAnswer' : ActorMethod<[RoomId, SdpAnswer], undefined>,
  'sendSdpOffer' : ActorMethod<[RoomId, SdpOffer], undefined>,
  'startVoiceSession' : ActorMethod<[RoomId], undefined>,
  'unblockUser' : ActorMethod<[User], undefined>,
  'unlinkAltAccount' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];