/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AvatarConfig {
  'backgroundColor' : string,
  'avatarType' : string,
  'color' : string,
  'textOverlays' : string,
}
export interface ChatRefreshPreference { 'pollingIntervalMs' : bigint }
export interface Message {
  'id' : MessageId,
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
  'roomId' : RoomId,
}
export type MessageId = bigint;
export interface Room {
  'id' : RoomId,
  'creator' : Principal,
  'name' : string,
  'createdAt' : Time,
}
export type RoomId = string;
export type ThemePreference = { 'dark' : null } |
  { 'systemDefault' : null } |
  { 'light' : null };
export type Time = bigint;
export interface UserPreferences {
  'theme' : ThemePreference,
  'chatRefresh' : ChatRefreshPreference,
}
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'avatar' : AvatarConfig,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRoom' : ActorMethod<[string], RoomId>,
  'fetchMessages' : ActorMethod<[RoomId, MessageId, bigint], Array<Message>>,
  'getCallerUserPreferences' : ActorMethod<[], [] | [UserPreferences]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listRooms' : ActorMethod<[], Array<Room>>,
  'postMessage' : ActorMethod<[RoomId, string], MessageId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCallerUserPreferences' : ActorMethod<[UserPreferences], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];