/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RoomId = IDL.Text;
export const MessageId = IDL.Nat;
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'roomId' : RoomId,
});
export const ThemePreference = IDL.Variant({
  'dark' : IDL.Null,
  'systemDefault' : IDL.Null,
  'light' : IDL.Null,
});
export const ChatRefreshPreference = IDL.Record({
  'pollingIntervalMs' : IDL.Nat,
});
export const UserPreferences = IDL.Record({
  'theme' : ThemePreference,
  'chatRefresh' : ChatRefreshPreference,
});
export const AvatarConfig = IDL.Record({
  'backgroundColor' : IDL.Text,
  'avatarType' : IDL.Text,
  'color' : IDL.Text,
  'textOverlays' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'avatar' : AvatarConfig,
});
export const Room = IDL.Record({
  'id' : RoomId,
  'creator' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRoom' : IDL.Func([IDL.Text], [RoomId], []),
  'fetchMessages' : IDL.Func(
      [RoomId, MessageId, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getCallerUserPreferences' : IDL.Func(
      [],
      [IDL.Opt(UserPreferences)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'postMessage' : IDL.Func([RoomId, IDL.Text], [MessageId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCallerUserPreferences' : IDL.Func([UserPreferences], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RoomId = IDL.Text;
  const MessageId = IDL.Nat;
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'roomId' : RoomId,
  });
  const ThemePreference = IDL.Variant({
    'dark' : IDL.Null,
    'systemDefault' : IDL.Null,
    'light' : IDL.Null,
  });
  const ChatRefreshPreference = IDL.Record({ 'pollingIntervalMs' : IDL.Nat });
  const UserPreferences = IDL.Record({
    'theme' : ThemePreference,
    'chatRefresh' : ChatRefreshPreference,
  });
  const AvatarConfig = IDL.Record({
    'backgroundColor' : IDL.Text,
    'avatarType' : IDL.Text,
    'color' : IDL.Text,
    'textOverlays' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'avatar' : AvatarConfig,
  });
  const Room = IDL.Record({
    'id' : RoomId,
    'creator' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRoom' : IDL.Func([IDL.Text], [RoomId], []),
    'fetchMessages' : IDL.Func(
        [RoomId, MessageId, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getCallerUserPreferences' : IDL.Func(
        [],
        [IDL.Opt(UserPreferences)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'postMessage' : IDL.Func([RoomId, IDL.Text], [MessageId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCallerUserPreferences' : IDL.Func([UserPreferences], [], []),
  });
};

export const init = ({ IDL }) => { return []; };